global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'search-service'
    static_configs:
      - targets: ['host.docker.internal:3004']

  - job_name: 'logging-service'
    static_configs:
      - targets: ['host.docker.internal:3005']
